---
- name: Get Security Group SSH
  amazon.aws.ec2_security_group_info:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": TEAM2_SSH
  register: sg_ssh_info
- name: Get Security Group HTTP
  amazon.aws.ec2_security_group_info:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    filters:
      "tag:Name": TEAM2_HTTP
  register: sg_http_info
- name: Debug sg_info
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - sg_ssh_info
    - sg_http_info
- name: set facts
  set_fact:
    sg_ssh: "{{ sg_ssh_info.security_groups[0] }}"
    sg_http: "{{ sg_http_info.security_groups[0] }}"
- name: Debug sg
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - sg_ssh
    - sg_http
