---
- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: TEAM2_VPC
    cidr_block: 10.2.0.0/16
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    tenancy: default
    tags:
      Name: TEAM2_VPC
      Team: TEAM2
  register: vpc
- name: Debug VPC
  ansible.builtin.debug:
    var: vpc
