---
- name: Check Target EC2
  ansible.builtin.debug:
    var: target_ec2
- name: Delete Target EC2
  amazon.aws.ec2_instance:
    region: "{{ region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    state: absent
    filters:
      "tag:Name": TEAM2-Target
  register: ec2_del
- name: Debug Del
  ansible.builtin.debug:
    var: ec2_del

