---
- name: Create Security group1
  amazon.aws.ec2_security_group:
    name: TEAM2_SSH
    region: "{{ region }}"
    vpc_id: "{{ vpc.id }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
    description: TEAM2 ssh group
    tags:
      Name: TEAM2_SSH
      Team: TEAM2
  register: sg_ssh
- name: Create Security group2
  amazon.aws.ec2_security_group:
    name: TEAM2_HTTP
    region: "{{ region }}"
    vpc_id: "{{ vpc.id }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: tcp
        ports:
          - 80
          - 443
          - 8080
        cidr_ip: 0.0.0.0/0
    description: TEAM2 http group
    tags:
      Name: TEAM2_HTTP
      Team: TEAM2
  register: sg_http
- name: Debug SG		
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - sg_ssh
    - sg_http    
- name: set facts		
  set_fact:
    sg_ssh: "{{ sg_ssh }}"
    sg_http: "{{ sg_http }}"

